services:
  db:
    image: mysql:8.1.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_ROOT_PASSWORD=asfgASFA42
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  api:
    container_name: user-details-service-api
    build:
      context: ./
    image: user-details-service
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/main
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_PASSWORD: asfgASFA42
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local